engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  fixme:
      enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
ratings:
  paths:
  - "**.es6"
  - "**.js"
  - "**.jsx"
exclude_paths:
- specs/**/*
- "**/vendor/**/*"